export const entityNameMap: Record<string, string> = {
    UnitOfMeasurement: "unit_of_measurement",
    Vendor: "vendor",
    Material: "material",
    BudgetHead: "budget_head",
    ProjectBudget: "project_budget",
    ScheduleSetup: "schedule_setup",
    ScheduleOfRates: "schedule_of_rates",
    ScheduleOfRatesLine: "schedule_of_rates_line",
    Task: "task",
    TaskImage: "task_image",
    TaskMeasurement: "task_measurement",
    BillOfQuantity: "bill_of_quantity",
    BillOfQuantityLine: "bill_of_quantity_line",
    File: "file",
    FilePermission: "file_permission",
    PurchaseOrder: "purchase_order",
    PurchaseOrderLine: "purchase_order_line",
    GoodReceivedNote: "good_received_note",
    MaterialIndent: "material_indent",
    WorkOrder: "work_order",
    WorkOrderLine: "work_order_line",
    WorkBilling: "work_billing",
    WorkBillingLine: "work_billing_line"
};