name: Backend Build Pipeline

on:
  push:
    branches:
      - fusionhub-NJs-backend
      # - main                   # uncomment when ready for production
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: [self-hosted, node-runner]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      # - name: Install cross-env
      #   run: npm install -g cross-env

      # - name: Run tests
      #   run: npx cross-env NODE_ENV=test npx jest --silent=false

      - name: Build
        run: npm run build
